apiVersion: v1
kind: Service
metadata:
  labels:
    app: wm-storage
    deploymentId: demo-service
  name: wm-clusterip-storage
  namespace: webmethods
spec:
  selector:
    app: wm-storage
  type: ClusterIP
  ports: 
  - name: iijdbc-connect
    port: 3306
    protocol: TCP
    targetPort: 3306