apiVersion: v1
kind: Service
metadata:
  labels:
    app: wm-demo-service
    deploymentId: demo-service
  name: wm-nodeport-demo-service
  namespace: webmethods
spec:
  selector:
    app: wm-demo-service
  type: NodePort
  ports: 
  - name: iadmin-port
    port: 5555
    protocol: TCP
    targetPort: 5555
    nodePort: 30055
