apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: webmethods
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: hostpath
